### ISSUE TITLE
comment data needed for hand coding

### ISSUE THREAD

**Issue by judgelord** [judgelord/rulemaking#6]
1. At least one observation per docket, sorted by docket, then org.type, then org.

- preview of attachment texts
- regulations.gov url for each comment

2. A script to pull in, modify, and update the google sheet (so that we can continue to apply coding rules).

Anything else? @mcneillucy

**Comment by mcneillucy** [comment]
6/17- half way through docket observations for FWS

**Comment by mcneillucy** [comment]
7/3- 
agencies that have two position examples per docket: EERE, NPS, FWS, EPA, FDA, VA, OSHA, ATF
agencies without two position examples per docket: IRS, CFPB, OTS, HHS, USCIS, CMS, ED, DOD, ETA, BLM, FNS, FAA, OCC, EBSA, SSA BSEE, OSM, BOEM, WHD, OMB, FEMA, FHWA, PHMSA, BIA, OFCCP, ACF, DOL, CDC, OPM, LMSO, CPSC, EEOC, MMS

**Comment by judgelord** [comment]
I implemented most of this in `comment_coding_sheets.R`(see also `rule_coding_sheets.R` for rule-level coding).
